# Independent service

Services:
  - Type: Independent
    Url: github.com/ahmetson/item.git
    Instance: static01
    Controllers:
      - Type: Replier # Replier or Pusher or Publisher or Router
        Name: "userApi"
        Instances:
          - Port: 2302
            Instance: ""
    Proxies:
      - Url: "auth"
        Instance: ""
        Port: 8000
      - Url: github.com/ahmetson/item.git
        Instance: ""
        Port: 8001
    # Proxy pipelines. If it's not given then the proxies won't be used.
    # The last node in the path should be the ControllerName
    Pipelines:
      - "auth->validator->userApi"

    Extensions:
      - Url: "database"
        Instance: ""
        Port: 8002